name: Bug Report
description: Feedback on encountered BUGs, abnormal phenomena in use, etc.
title: "[Bug]: "
labels: ["bug"]
assignees:
  - dawn-lc
body:
  - type: checkboxes
    id: checks
    attributes:
      label: Before Reporting...
      options:
      - label: I have spent at least 5 minutes thinking and preparing before submitting this issue.
        required: true
      - label: I have read the relevant documentation and searched existing issues.
        required: true
      - label: I understand that if I do not provide enough information, the issue may be ignored.
        required: true
  - type: textarea
    id: describe
    attributes:
      label: Describe Your Issue
      description: Briefly describe the issue you are experiencing.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      value: |
        1. Go to '...'
        2. Click on '...'
        3. The issue appears.
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: Which browser are you using?
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Other (e.g., XXXSpeed, XXXSecure, etc.)
    validations:
      required: true
  - type: dropdown
    id: scriptManager
    attributes:
      label: Which script manager are you using?
      options:
        - Tampermonkey
        - Tampermonkey Beta
        - ScriptCat
        - Violentmonkey
        - Other
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: What is the script version?
      placeholder: e.g., 3.1.1
    validations:
      required: true
  - type: dropdown
    id: downloadMode
    attributes:
      label: What is the download mode?
      options:
        - Aria2
        - IwaraDownloader
        - Browser
        - Others
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Open developer tools and copy-paste the relevant logs here.
      render: Text
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: |
        If available, add screenshots to help explain your issue.
        Tip: You can click this area and drag your screenshot file into it to upload the image.
    validations:
      required: false
  - type: textarea
    id: others
    attributes:
      label: Other Information
      description: |
        Any related configurations, links, or references?
        Anything that helps us understand the issue better.
        Tip: You can click this area and drag files into the text box to upload and share them.
    validations:
      required: false
