name: Preview
on:
  push:
    branches: 
      - dev
    paths:
      - 'src/*'
      - 'build/*'
      - 'utils/*'
      - '.github/workflows/*'
env:
  release_tag: preview
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  Update:
    if: github.actor != 'github-actions'
    runs-on: ubuntu-latest
    steps:
    - name: 初始化Node.js环境
      uses: actions/setup-node@v4
    - name: 拉取最新代码
      uses: actions/checkout@v4
      with:
        ref: dev
    - run: |
        git config --global user.name github-actions
        git config --global user.email github-actions@github.com
    - name: 修改版本号
      run: npm version patch
    - name: 保存版本号
      run: |
        git add .
        git commit --amend --no-edit
        git push --force
  Release:
    needs: Update
    if: github.actor != 'github-actions'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: 初始化Node.js环境
      uses: actions/setup-node@v4
    - name: 拉取最新代码
      uses: actions/checkout@v4
      with:
        ref: dev
    - name: 预处理
      run: npm run preprocess -- $release_tag
    - name: 安装依赖项
      run: npm ci
    - name: 编译
      run: npm run build
    - name: 后处理
      run: npm run postprocess
    - uses: martinbeentjes/npm-get-version-action@v1.3.1
      id: package-version
    - name: 标记当前版本
      uses: ncipollo/release-action@v1
      with:
        generateReleaseNotes: true
        token: ${{ secrets.GITHUB_TOKEN }}
        name: "[Pre-release] ${{ steps.package-version.outputs.current-version }}"
        tag: "v${{ steps.package-version.outputs.current-version }}"
        artifacts: "temp/*"
    - name: 删除旧版本
      run: gh release delete ${{ env.release_tag }} --cleanup-tag --yes
    - name: 发布新版本
      uses: ncipollo/release-action@v1
      with:
        prerelease: true
        generateReleaseNotes: true
        token: ${{ secrets.GITHUB_TOKEN }}
        name: "预览版/Pre-release"
        tag: ${{ env.release_tag }}
        artifacts: "temp/*"