name: Preview
on:
  push:
    branches: 
      - dev
    paths:
      - 'src/*'
      - 'build/*'
      - 'utils/*'
      - '.github/workflows/*'
env:
  release_tag: preview
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  Release:
    permissions:
      contents: write
    if: github.actor != 'github-actions'
    runs-on: ubuntu-latest
    steps:
    - name: 初始化Node.js环境
      uses: actions/setup-node@v4
    - name: 拉取最新代码
      uses: actions/checkout@v4
      with:
        ref: dev
    - name: 预处理
      run: npm run preprocess -- ${{ env.release_tag }}
    - name: 安装依赖项
      run: npm ci
    - name: 编译
      run: npm run build
    - name: 后处理
      run: npm run postprocess
    - name: 获取版本号
      uses: martinbeentjes/npm-get-version-action@v1.3.1
      id: package-version
    - name: 删除旧版本
      run: gh release delete ${{ env.release_tag }} --cleanup-tag --yes
    - name: 发布新版本
      run: gh release create ${{ env.release_tag }} temp\IwaraDownloadTool.min.user.js temp\IwaraDownloadTool.mata.js temp\IwaraDownloadTool.user.js --prerelease --target dev --title "预览版/Pre-release ${{ steps.package-version.outputs.current-version }}" --notes "Full Changelog [${{ env.release_tag }}](https://github.com/dawn-lc/IwaraDownloadTool/commits/${{ env.release_tag }})"