name: Preview
on:
  push:
    branches: 
      - dev
    paths:
      - 'src/*'
      - 'build/*'
      - 'utils/*'
env:
  release-tag: preview 
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  Release:
    permissions:
      contents: write
    if: github.actor != 'github-actions'
    runs-on: ubuntu-latest
    steps:
    - name: 初始化Node.js环境
      uses: actions/setup-node@v4
    - name: 拉取最新代码
      uses: actions/checkout@v4
      with:
        ref: dev
    - name: 预处理
      run: npm run preprocess -- ${{ env.release_tag }}
    - name: 安装依赖项
      run: npm ci
    - name: 编译
      run: npm run build
    - name: 后处理
      run: npm run postprocess
    - name: 获取编译结果
      run: |
        FILES=$(find temp -type f | tr '\n' ' ')
        echo "file-list=${FILES}" >> $GITHUB_ENV
    - name: 获取版本号
      uses: martinbeentjes/npm-get-version-action@v1.3.1
    - name: 删除旧版本
      run: gh release delete ${{ env.release-tag }} --cleanup-tag --yes
      continue-on-error: true
    - name: 发布新版本
      run: |
        gh release create ${{ env.release-tag }} ${{ env.file-list }} \
          --prerelease \
          --title "预览版/Release ${{ steps.package-version.outputs.current-version}}" \
          --notes "Full Changelog [${{ env.release-tag }}](https://github.com/dawn-lc/IwaraDownloadTool/commits/${{ env.release-tag }})"