name: Release
on:
  push:
    branches: 
      - master
    paths:
      - 'src/*'
      - 'build/*'
      - 'utils/*'
env:
  release_tag: latest
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  Release:
    permissions:
      contents: write
    if: github.actor != 'github-actions'
    runs-on: ubuntu-latest
    steps:
    - name: 初始化Node.js环境
      uses: actions/setup-node@v4
    - name: 拉取最新代码
      uses: actions/checkout@v4
      with:
        ref: master
    - name: 预处理
      run: npm run preprocess -- ${{ env.release_tag }}
    - name: 安装依赖项
      run: npm ci
    - name: 编译
      run: npm run build
    - name: 获取编译结果
      run: |
        FILES=$(find temp -type f | tr '\n' ' ')
        echo "file_list=${FILES}" >> $GITHUB_ENV
    - name: 获取版本号
      run: |
        PACKAGE_VERSION=$(cat package.json | jq '.version' | tr -d '"')
        echo "current_version=${PACKAGE_VERSION}" >> $GITHUB_ENV
    - name: 删除旧版本
      run: gh release delete ${{ env.release_tag }} --cleanup-tag --yes
      continue-on-error: true
    - name: 发布新版本
      run: |
        gh release create ${{ env.release_tag }} ${{ env.file_list }} \
          --latest \
          --title "正式版/Release ${{ env.current_version}}" \
          --notes "Full Changelog [${{ env.release_tag }}](https://github.com/dawn-lc/IwaraDownloadTool/commits/${{ env.release_tag }})"