name: Release
on:
  push:
    branches: 
      - master
    paths:
      - 'src/*'
      - 'build/*'
      - '.github/workflows/*'
env:
  release_tag: latest
jobs:
  Release:
    if: github.actor != 'github-actions'
    runs-on: ubuntu-latest
    steps:
    - name: 初始化Node.js环境
      uses: actions/setup-node@v4
    - name: 拉取最新代码
      uses: actions/checkout@v4
      with:
        ref: master
    - name: 预处理
      run: npm run preprocess -- $release_tag
    - name: 安装依赖项
      run: npm ci
    - name: 编译
      run: npm run build
    - name: 后处理
      run: npm run postprocess
    - uses: martinbeentjes/npm-get-version-action@v1.3.1
      id: package-version
    - name: 删除旧版本
      run: gh release delete ${{ env.release_tag }} --cleanup-tag --yes
    - name: 更新标签
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        prerelease: false
        generateReleaseNotes: true
        token: ${{ secrets.GITHUB_TOKEN }}
        name: "正式版/Release"
        tag: ${{ env.release_tag }}
        artifacts: "temp/*"