name: Release
on:
  push:
    branches: 
      - master
    paths:
      - 'src/*'
      - 'build/*'
      - '.github/workflows/*'
env:
  release_tag: latest
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  Release:
    permissions:
      contents: write
    if: github.actor != 'github-actions'
    runs-on: ubuntu-latest
    steps:
    - name: 初始化Node.js环境
      uses: actions/setup-node@v4
    - name: 拉取最新代码
      uses: actions/checkout@v4
      with:
        ref: master
    - name: 预处理
      run: npm run preprocess -- $release_tag
    - name: 安装依赖项
      run: npm ci
    - name: 编译
      run: npm run build
    - name: 后处理
      run: npm run postprocess
    - name: 获取版本号
      uses: martinbeentjes/npm-get-version-action@v1.3.1
      id: package-version
    - name: 删除旧版本
      uses: dev-drprasad/delete-tag-and-release@v0.2.1
      with:
        delete_release: true
        tag_name: ${{ env.release_tag }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: 发布新版本
      uses:  ncipollo/release-action@v1
      with:
        prerelease: false
        makeLatest: true
        draft: false
        removeArtifacts: true
        token: ${{ secrets.GITHUB_TOKEN }}
        name: "正式版/Release ${{ steps.package-version.outputs.current-version }}"
        body: "Full Changelog: [${{ env.release_tag }}](https://github.com/dawn-lc/IwaraDownloadTool/commits/${{ env.release_tag }})"
        tag: ${{ env.release_tag }}
        artifacts: "temp/*"